name: parking_lot_joao
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0-260.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.2
  flutter_native_splash: ^2.3.10
  cupertino_icons: ^1.0.6
  get_it: ^7.6.7
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  intl: ^0.19.0
  dio: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  bloc_test: ^9.1.0
  mockito: ^5.4.4

flutter_native_splash:
  color: "#4974E5"
  image: assets/images/logo.png
  android_12:
    color: "#4974E5"
    image: assets/images/logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
